export const state = {
  rabbits: [],
  food: [],
  particles: [],
  terrain: [],
  history: [],
  tick: 0,
  births: 0,
  deaths: 0,
  running: true,
  simSpeed: 1,
  foodTarget: 145,
  mutationRate: 0.07,
  predatorPressure: 0.16,
  mateSelectivity: 0.35,
  climate: "stable",
  pressure: "low",
  seasons: true,
  droughtTimer: 0,
  camera: {
    x: 0,
    y: 0,
    zoom: 1,
    drag: false,
    lastX: 0,
    lastY: 0,
  },
};
